### ISSUE TITLE
JLPCB Bill of Materials for Assembly

### ISSUE THREAD

**Issue by rohankapoorcom** [Hypfer/valetudo-dreameadapter#3]
Hi Hypfer,

Thanks for putting these together. I was looking at having JLPCB build a set of boards for my own use rather than just having them make the PCB and assembling the components myself. Do you by chance have a list of part numbers from their library that could be uploaded to have them handle the assembly?

If you don't already, I can try to find them and will upload that list here.

Thanks!

**Comment by Hypfer** [comment]
I don't have such a BOM because I just ordered the components from randomly chosen Aliexpress listings.

Tbh I also don't think that it would be a good idea to have anything specific to JLCPCB in this repo, as they're just another private company and that would be at the very least free marketing for them.
I'm happy with their products but I don't want to funnel customers their way and kinda lock-in those who are new to ordering PCBs for home use into that one vendor.
Because that's what would happen with a list of components that has JLCPCB-specific part numbers. Newcomers especially would just stick to that list for that vendor because they want to do the right thing and not take any risks there.


Oh and beside that I also believe that this is a great project to start learning how to solder. It would be bad to take away that opportunity for newcomers to learn that valuable skill by providing a path of less resistance.
That's why it's all THT after all. If relying on such a service would've been the goal, it could've been SMD

**Comment by Mr-Newlove** [comment]
Hey Hypfer,

Sorry to comment on a old issue. But even just manufacturer part numbers for anything I am sure would be helpful for people.

Here is the list I made that should be available from typical part sources like digikey, mouser, arrow...

    J1.1/J1.2 : 2PH2-16-UA     Adam Tech
    J2 : 61300811821     Würth Elektronik
    J3 : 61300811821     Würth Elektronik   ** YES, 2 of them
    J4 : MicroUSB: 614105150721     Würth Elektronik
    J5 : USB-B: USB-A1VSB6     On Shore Technology Inc.
    JP1/JP2(pins) : PR20C04VBNN     METZ CONNECT USA Inc. <just cut in half
    JP1/JP2(jumpers) : SPN02SXCN-RC     Sullins Connector Solutions
    SW1 : 1301.9302     SCHURTER Inc.

**Comment by RealKeyboardWarrior** [comment]
@Mr-Newlove 

You've saved me so much time and frustration, thank you so much ❤️

**Comment by B48D81EFCC** [comment]
@Mr-Newlove Thanks a lot.
Took me a long time to find the correct parts (bought some wrong parts already). Thanks!
